FROM ubuntu:latest

ARG download_url

RUN wget https://raw.githubusercontent.com/joshfranzen/MinecraftBedrockServer/Containerization/Containerize/SetupMinecraft.sh
 && chmod +x SetupMinecraft.sh
 && ./SetupMinecraft.sh
 
EXPOSE 19132/udp

WORKDIR /bedrock-server
ENV LD_LIBRARY_PATH=.
CMD ./bedrock_server